return {
["THANKYOU!"] = {
        Rewards = {
                Gems = 400,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 19,
            min = 0,
            hour = 14,
            sec = 0,
        })
    },

["RELEASE!"] = {
        Rewards = {
                Gems = 400,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 21,
            min = 0,
            hour = 18,
            sec = 0,
        })
    },

["UNRIVALED!"] = {
        Rewards = {
                Gems = 200,
                Rerolls = 5,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 24,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["40kCCU!"] = {
        Rewards = {
                Gems = 4000,
                Rerolls = 40,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 17,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
}
