return {
    ["HeadlessIsCool"] = {
        Rewards = {
            Gems = 69,
            Coins = 420,
            Rerolls = 2,
        },

        Expiration = os.time({
            year = 2026,
            month = 1,
            day = 1,
            min = 0,
            hour = 0,
            sec = 0,
        })
    },

["SorryEA!"] = {
        Rewards = {
            Gems = 2000,
            Rerolls = 40,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 13,
            min = 0,
            hour = 7,
            sec = 0,
        })
    },

["SorryEA2!"] = {
        Rewards = {
            Gems = 3000,
            Rerolls = 60,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 13,
            min = 0,
            hour = 7,
            sec = 0,
        })
    },

}
