return {
["THANKYOU!"] = {
        Rewards = {
                Gems = 400,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 19,
            min = 0,
            hour = 14,
            sec = 0,
        })
    },

["RELEASE!"] = {
        Rewards = {
                Gems = 400,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 21,
            min = 0,
            hour = 18,
            sec = 0,
        })
    },

["UNRIVALED!"] = {
        Rewards = {
                Gems = 200,
                Rerolls = 5,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 24,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

["40kCCU!"] = {
        Rewards = {
                Gems = 4000,
                Rerolls = 40,
        },

        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 15,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["Universal!"] = {
    Rewards = {
                Gems = 450,
                Rerolls = 15,
        },
       
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 22,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["NumberOne!"] = {
    Rewards = {
                Gems = 500,
                Rerolls = 15,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 22,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["Mainstream!"] = {
    Rewards = {
                Gems = 450,
                Rerolls = 15,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 25,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },
["ThankYouUTD!"] = {
    Rewards = {
                Gems = 400,
                Rerolls = 5,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 22,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["FixingBugs!"] = {
    Rewards = {
                Gems = 450,
                Rerolls = 25,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 18,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["75kLikes!"] = {
    Rewards = {
                Gems = 400,
                Rerolls = 10,
        },
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 22,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["ThousandsOfCodes!"] = {
    Rewards = {
                Gems = 800,
                Rerolls = 15,
        },
        LevelRequirement = 5,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 21,
            min = 0,
            hour = 20,
            sec = 0,
        })
    },

["SixSeven!"] = {
    Rewards = {
                Rerolls = 67,
        },
        LevelRequirement = 15,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 19,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["MaxedOut!"] = {
    Rewards = {
                 Gems = 600,
                Rerolls = 10,
        },
        LevelRequirement = 5,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 24,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },
["testEA"] = {
    Rewards = {
                 Gems = 6,
        },
        RequiresEA = true,
        Expiration = os.time({
            year = 2025,
            month = 12,
            day = 24,
            min = 0,
            hour = 12,
            sec = 0,
        })
    },

}
